# version: '3'

services:
  frontend:
    build:
      context: frontend
      dockerfile: dev.dockerfile
    env_file: .env
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/package.json

  backend:
    build:
      context: backend
    command: ${TEST}
    env_file: .env
    develop:
      watch:
        - action: rebuild
          path: ./backend
    restart: on-failure

  database:
    build:
      context: database
    environment:
      MYSQL_TCP_PORT: '${DB_PORT:?error}'
      MARIADB_USER: '${DB_USER:?error}'
      MARIADB_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:?error}'
      MARIADB_PASSWORD: '${DB_PASSWORD:?error}'
      MARIADB_DATABASE: '${DB_DATABASE:?error}'
    develop:
      watch:
        - action: rebuild
          path: ./database/Rubrics_DB.sql
    stop_signal: SIGKILL
    image: mariadb:latest
    restart: unless-stopped
    ports:
      # Make the DB accessible from outside of the Docker network if needed
      - 3307:3306
    volumes:
      # Mount the db_schema directory into the container to be auto-read and created in the new db
      - './database/Rubrics_DB.sql:/docker-entrypoint-initdb.d/Rubrics_DB.sql'
    env_file:
      - .env

  adminer:
    image: adminer
    ports:
      - '${DB_WEB_PORT:?error}:8080'
    environment:
      ADMINER_DEFAULT_SERVER: 'database:${DB_PORT}'

  proxy:
    image: dockerhub.csc.ncsu.edu/ignacioxd/apacheshib-proxy
    env_file: .env
    ports:
      - '443:443'
      - '${FRONTEND_PORT}:${FRONTEND_PORT:?error}'
    environment:
      LOGIN_PATH: '${PROXY_AUTH_PATH:?error}'
      FRONTEND_PORT: '${FRONTEND_PORT}'
      FRONTEND_HOST: '${PROXY_FRONTEND_HOSTNAME:?error}'
      BACKEND_HOST: '${PROXY_BACKEND_HOSTNAME:?error}'

    stop_signal: SIGKILL
